export const STATION_ARR: string[] = [
  "Ahangama",
  "Aluthgama",
  "Ambalangoda",
  "Ambewela",
  "Anuradhapura",
  "Anuradhapura Town",
  "Avissawella",
  "Badulla",
  "Bandarawela",
  "Batticaloa",
  "Beliatta",
  "Bentota",
  "Beruwala",
  "China bay",
  "Chunnakam",
  "Colombo Fort",
  "Demodara-Ella",
  "Diyathalawa",
  "Ella",
  "Eraur",
  "Galgamuwa",
  "Galle",
  "Galoya",
  "Gampaha",
  "Gampola",
  "Habaraduwa",
  "Habarana",
  "Hali Ela",
  "Haputhale",
  "Hatton",
  "Hikkaduwa",
  "Hingurakgoda",
  "Jaffna",
  "Kakirawa",
  "Kalutara South",
  "Kamburugamuwa",
  "Kandy",
  "Kankesanthurai",
  "Kanthale",
  "Kilinochchi",
  "Kodikamam",
  "Koggala",
  "Kurunegala",
  "Madhupara",
  "Mahawa",
  "Makumbura",
  "Mannar",
  "Maradhana",
  "Matale",
  "Matara",
  "Medawachchiya",
  "Mirigama",
  "Mirissa",
  "Moratuwa",
  "Mount Lavinia",
  "NAGOLLAGAMA",
  "Nanu Oya",
  "Nawalapitiya",
  "Nawalapitya",
  "Nugegoda",
  "Omantha",
  "Pallai",
  "Panadura",
  "Peradeniya",
  "Polgahawela",
  "Polonnaruwa",
  "Puwakpitiya",
  "Ragama",
  "Rambukkana",
  "Rathmalana",
  "Return Colombo",
  "Return Waga",
  "Talaimannar Pier",
  "Thambalagamuwa",
  "Thambuththegama",
  "Thandikulam",
  "Trincomalee",
  "Unawatuna",
  "Valachchena",
  "Vauniya",
  "Veyangoda",
  "Waduwwa",
  "Weligama",
  "Welikanda",
  "Wellawa",
  "Wellawatte",
];
