export const STATION_OBJ: { value: string; label: string }[] = [
  { value: "Ahangama", label: "Ahangama" },
  { value: "Aluthgama", label: "Aluthgama" },
  { value: "Ambalangoda", label: "Ambalangoda" },
  { value: "Ambewela", label: "Ambewela" },
  { value: "Anuradhapura", label: "Anuradhapura" },
  { value: "Anuradhapura Town", label: "Anuradhapura Town" },
  { value: "Avissawella", label: "Avissawella" },
  { value: "Badulla", label: "Badulla" },
  { value: "Bandarawela", label: "Bandarawela" },
  { value: "Batticaloa", label: "Batticaloa" },
  { value: "Beliatta", label: "Beliatta" },
  { value: "Bentota", label: "Bentota" },
  { value: "Beruwala", label: "Beruwala" },
  { value: "China bay", label: "China bay" },
  { value: "Chunnakam", label: "Chunnakam" },
  { value: "Colombo Fort", label: "Colombo Fort" },
  { value: "Demodara-Ella", label: "Demodara-Ella" },
  { value: "Diyathalawa", label: "Diyathalawa" },
  { value: "Ella", label: "Ella" },
  { value: "Eraur", label: "Eraur" },
  { value: "Galgamuwa", label: "Galgamuwa" },
  { value: "Galle", label: "Galle" },
  { value: "Galoya", label: "Galoya" },
  { value: "Gampaha", label: "Gampaha" },
  { value: "Gampola", label: "Gampola" },
  { value: "Habaraduwa", label: "Habaraduwa" },
  { value: "Habarana", label: "Habarana" },
  { value: "Hali Ela", label: "Hali Ela" },
  { value: "Haputhale", label: "Haputhale" },
  { value: "Hatton", label: "Hatton" },
  { value: "Hikkaduwa", label: "Hikkaduwa" },
  { value: "Hingurakgoda", label: "Hingurakgoda" },
  { value: "Jaffna", label: "Jaffna" },
  { value: "Kakirawa", label: "Kakirawa" },
  { value: "Kalutara South", label: "Kalutara South" },
  { value: "Kamburugamuwa", label: "Kamburugamuwa" },
  { value: "Kandy", label: "Kandy" },
  { value: "Kankesanthurai", label: "Kankesanthurai" },
  { value: "Kanthale", label: "Kanthale" },
  { value: "Kilinochchi", label: "Kilinochchi" },
  { value: "Kodikamam", label: "Kodikamam" },
  { value: "Koggala", label: "Koggala" },
  { value: "Kurunegala", label: "Kurunegala" },
  { value: "Madhupara", label: "Madhupara" },
  { value: "Mahawa", label: "Mahawa" },
  { value: "Makumbura", label: "Makumbura" },
  { value: "Mannar", label: "Mannar" },
  { value: "Maradhana", label: "Maradhana" },
  { value: "Matale", label: "Matale" },
  { value: "Matara", label: "Matara" },
  { value: "Medawachchiya", label: "Medawachchiya" },
  { value: "Mirigama", label: "Mirigama" },
  { value: "Mirissa", label: "Mirissa" },
  { value: "Moratuwa", label: "Moratuwa" },
  { value: "Mount Lavinia", label: "Mount Lavinia" },
  { value: "NAGOLLAGAMA", label: "NAGOLLAGAMA" },
  { value: "Nanu Oya", label: "Nanu Oya" },
  { value: "Nawalapitiya", label: "Nawalapitiya" },
  { value: "Nawalapitya", label: "Nawalapitya" },
  { value: "Nugegoda", label: "Nugegoda" },
  { value: "Omantha", label: "Omantha" },
  { value: "Pallai", label: "Pallai" },
  { value: "Panadura", label: "Panadura" },
  { value: "Peradeniya", label: "Peradeniya" },
  { value: "Polgahawela", label: "Polgahawela" },
  { value: "Polonnaruwa", label: "Polonnaruwa" },
  { value: "Puwakpitiya", label: "Puwakpitiya" },
  { value: "Ragama", label: "Ragama" },
  { value: "Rambukkana", label: "Rambukkana" },
  { value: "Rathmalana", label: "Rathmalana" },
  { value: "Return Colombo", label: "Return Colombo" },
  { value: "Return Waga", label: "Return Waga" },
  { value: "Talaimannar Pier", label: "Talaimannar Pier" },
  { value: "Thambalagamuwa", label: "Thambalagamuwa" },
  { value: "Thambuththegama", label: "Thambuththegama" },
  { value: "Thandikulam", label: "Thandikulam" },
  { value: "Trincomalee", label: "Trincomalee" },
  { value: "Unawatuna", label: "Unawatuna" },
  { value: "Valachchena", label: "Valachchena" },
  { value: "Vauniya", label: "Vauniya" },
  { value: "Veyangoda", label: "Veyangoda" },
  { value: "Waduwwa", label: "Waduwwa" },
  { value: "Weligama", label: "Weligama" },
  { value: "Welikanda", label: "Welikanda" },
  { value: "Wellawa", label: "Wellawa" },
  { value: "Wellawatte", label: "Wellawatte" },
];
